SELECT 
HAOU.NAME AS "ORGANIZATION",
HZP.PARTY_NAME AS "SUPPLIER",
POS.SEGMENT1 AS "SUPPLIER NUMBER",
HZPS.PARTY_SITE_NAME AS "SITE",
HZP.CITY||','||HZP.STATE||','||HZP.COUNTRY AS "SITE ADDRESS",
APIA.INVOICE_NUM AS "INVOICE NUMBER",
TO_CHAR(APIA.INVOICE_DATE, 'DD-MM-YYYY') AS "INVOICE DATE", 
APIA.INVOICE_TYPE_LOOKUP_CODE AS "INVOICE TYPE",
TO_CHAR(APIA.GL_DATE, 'DD-MM-YYYY') AS "LEDGER DATE",
TO_CHAR(APSA.DUE_DATE, 'DD-MM-YYYY') AS "DUE DATE",
APIA.INVOICE_AMOUNT AS "INVOICE AMOUNT",
(APIA.INVOICE_AMOUNT - APSA.AMOUNT_REMAINING) AS "AMOUNT PAID",
APSA.AMOUNT_REMAINING AS BALANCE_AMOUNT,
TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) - TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') ) AS "PAST DUE DAYS",
CASE WHEN TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )>= -999 AND
TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )<0
THEN APSA.AMOUNT_REMAINING ELSE 0 END "Current Bucket",
CASE WHEN TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') ) >= 0 AND
TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )<= 30
THEN APSA.AMOUNT_REMAINING ELSE 0 END "0 to 30 Days",
CASE WHEN TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )>= 31 AND
TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )<= 60
THEN APSA.AMOUNT_REMAINING ELSE 0
END "31 to 60 Days",
CASE WHEN TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )>= 61 AND
TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )<= 90
THEN APSA.AMOUNT_REMAINING ELSE 0
END "61 to 90 Days",
CASE WHEN TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )>= 91 AND
TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )<= 120
THEN APSA.AMOUNT_REMAINING ELSE 0
END "91 to 120 Days",
CASE WHEN TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )>= 121 AND
TO_DATE(TO_CHAR(:AS_OF_DATE,'YYYY-MM-DD')) -   TO_DATE(TO_CHAR(APSA.DUE_DATE,'YYYY-MM-DD') )<= 999999
THEN APSA.AMOUNT_REMAINING ELSE 0
END "More than 120 Days"


FROM
HR_ALL_ORGANIZATION_UNITS HAOU,
HZ_PARTIES HZP,
HZ_PARTY_SITES HZPS,
POZ_SUPPLIERS POS,
AP_INVOICES_ALL APIA,
AP_PAYMENT_SCHEDULES_ALL APSA

WHERE 1=1
AND APIA.ORG_ID = HAOU.ORGANIZATION_ID(+)
AND APIA.PARTY_ID = HZP.PARTY_ID(+)
AND APIA.PARTY_SITE_ID = HZPS.PARTY_SITE_ID(+)
AND APIA.VENDOR_ID = POS.VENDOR_ID(+)
AND APIA.INVOICE_ID = APSA.INVOICE_ID(+)
AND HAOU.NAME = NVL (:ORG_NAME,HAOU.NAME)
AND APIA.GL_DATE <= NVL( :AS_OF_DATE,TRUNC(SYSDATE))
AND APIA.INVOICE_TYPE_LOOKUP_CODE = NVL( :INVOICE_TYPE,APIA.INVOICE_TYPE_LOOKUP_CODE)
AND APIA.INVOICE_AMOUNT >= NVL( :MIN_AMT,0)
AND APIA.INVOICE_AMOUNT <= NVL( :MAX_AMT,999999)


AND APSA.AMOUNT_REMAINING != APIA.INVOICE_AMOUNT
AND APSA.AMOUNT_REMAINING > 0
AND APIA.GL_DATE != APSA.DUE_DATE

ORDER BY 
POS.SEGMENT1,
APIA.INVOICE_NUM
============================================================================================================
INVOICE_TYPE:
SELECT DISTINCT INVOICE_TYPE_LOOKUP_CODE FROM AP_INVOICES_ALL

ORG_NAME:
SELECT DISTINCT INVOICE_TYPE_LOOKUP_CODE FROM AP_INVOICES_ALL

=======================================================================================================================
