SELECT DISTINCT 
POH.SEGMENT1,
TO_CHAR(POH.APPROVED_DATE,'DD-MM-YYYY') AS APPROVED_DATE,
TO_CHAR(POL.CLOSED_DATE,'DD-MM-YYYY') AS CLOSED_DATE,
POL.LINE_STATUS,
POL.PRC_BU_ID,
POL.REQ_BU_ID,
POL.LINE_NUM,
POL.QUANTITY,
POL.UNIT_PRICE,
TO_CHAR(POLL.NEED_BY_DATE,'DD-MM-YYYY') AS NEED_BY_DATE,
TO_CHAR(POLL.PROMISED_DATE,'DD-MM-YYYY') AS PROMISED_DATE,
TO_CHAR(POLL.REQUESTED_SHIP_DATE,'DD-MM-YYYY') AS REQUESTED_SHIP_DATE,
TO_CHAR(POLL.PROMISED_SHIP_DATE,'DD-MM-YYYY') AS PROMISED_SHIP_DATE,
TO_CHAR(POLL.CLOSED_FOR_RECEIVING_DATE,'DD-MM-YYYY') AS CLOSED_FOR_RECEIVING_DATE,
POLL.QUANTITY_RECEIVED,
POLL.QUANTITY_ACCEPTED,
POLL.QUANTITY_REJECTED,
EGPSIB.ITEM_NUMBER,
POD.QUANTITY_CANCELLED,
POD.DESTINATION_SUBINVENTORY,
POD.QUANTITY_BILLED,
POD.AMOUNT_BILLED,
RSH.RECEIPT_NUM, 
PPNF.FULL_NAME,
HZP.PARTY_NAME,
HZP.PARTY_NUMBER,
HZPS.PARTY_SITE_NAME,
HRO.NAME

FROM 
PO_HEADERS_ALL POH,
PO_LINES_ALL POL,
PO_LINE_LOCATIONS_ALL  POLL,
EGP_SYSTEM_ITEMS_B EGPSIB,
PO_DISTRIBUTIONS_ALL POD, 
RCV_SHIPMENT_HEADERS RSH,
PER_PERSON_NAMES_F PPNF, 
HZ_PARTIES HZP,
HZ_PARTY_SITES HZPS,
HR_ALL_ORGANIZATION_UNITS HRO,
POZ_SUPPLIERS POS

WHERE
POH.PO_HEADER_ID = POL.PO_HEADER_ID(+)
AND POL.PO_LINE_ID = POLL.PO_LINE_ID
AND POL.ITEM_ID = EGPSIB.INVENTORY_ITEM_ID(+)
AND POL.PO_LINE_ID = POD.PO_LINE_ID(+)
AND POH.VENDOR_ID = RSH.VENDOR_ID(+)
AND POH.AGENT_ID = PPNF.PERSON_ID
AND POH.VENDOR_ID = POS.VENDOR_ID
AND POS.PARTY_ID = HZP.PARTY_ID
AND HZP.PARTY_ID = HZPS.PARTY_ID(+)
AND POH.PRC_BU_ID = HRO.ORGANIZATION_ID
AND HRO.NAME = NVL(:ORGANIZATION,HRO.NAME)
AND POL.LINE_STATUS = NVL(:LINE_STATUS,POL.LINE_STATUS)
AND POH.APPROVED_DATE >= NVL(:APPROVAL_START_DATE,POH.APPROVED_DATE)
AND POH.APPROVED_DATE <= NVL(:APPROVAL_END_DATE,POH.APPROVED_DATE)
AND POL.CLOSED_DATE >= NVL(:LINE_CLOSED_START_DATE,POL.CLOSED_DATE)
AND POL.CLOSED_DATE <= NVL(:LINE_CLOSED_END_DATE,POL.CLOSED_DATE)
AND HRO.NAME IN('Supremo US Business Unit', 'France Business Unit', 'UK Business Unit','US1 Business Unit')
AND POL.LINE_STATUS IN ('OPEN','CLOSED')
AND ROWNUM<100