Supplier/PO/AP :

1. --Build a query for Inactive supplier List
SELECT VENDOR_NAME,STATUS 
FROM POZ_SUPPLIERS_V POS,HZ_PARTIES HZP
WHERE POS.PARTY_ID = HZP.PARTY_ID
AND HZP.STATUS = 'I'

2. --Build a query for Supplier List those who are Inactivated during last 2 months



3. --Get the Inactive Supplier Site List
SELECT HZS.PARTY_SITE_NAME,STATUS 
FROM HZ_PARTY_SITES HZS,POZ_SUPPLIER_SITES_V POS
WHERE HZS.PARTY_SITE_ID = POS.PARTY_SITE_ID
AND HZS.STATUS = 'I'

4. --Build a Query for the Supplier Type other than ‘SUPPLIER’
SELECT VENDOR_TYPE_LOOKUP_CODE FROM POZ_SUPPLIERS
WHERE VENDOR_TYPE_LOOKUP_CODE NOT IN ('SUPPLIER')

5. --Build a Query for Suppliers those are not having Supplier Site
SELECT VENDOR_NAME 
FROM POZ_SUPPLIERS_V
WHERE VENDOR_ID IN 
(SELECT VENDOR_ID 
FROM POZ_SUPPLIERS_V
MINUS
SELECT VENDOR_ID 
FROM POZ_SUPPLIER_SITES_V)

6. --Build a Query for Supplier contact
SELECT DISTINCT VENDOR_NAME,ADDRESS_LINE1,COUNTRY,CITY,ZIP 
FROM POZ_SUPPLIER_SITES_V POSS,POZ_SUPPLIERS_V POS 
WHERE POSS.VENDOR_ID(+) = POS.VENDOR_ID

7. --Write a Query for Supplier and its site List those are assigned to Vision Corporation Business Unit
SELECT DISTINCT NAME,VENDOR_NAME,PARTY_SITE_NAME
FROM HR_ALL_ORGANIZATION_UNITS HRO,POZ_SUPPLIERS_V POS,HZ_PARTY_SITES HZP
WHERE HRO.OBJECT_VERSION_NUMBER = POS.OBJECT_VERSION_NUMBER
AND HZP.PARTY_ID = POS.PARTY_ID
AND NAME = 'Vision Corporation'

8. --Write a query for the supplier’s having Purchase order value more than 1000$
SELECT  VENDOR_NAME,SUM(UNIT_PRICE * QUANTITY) AS TOTAL_AMOUNT
FROM PO_LINES_ALL POL,PO_HEADERS_ALL POH,POZ_SUPPLIERS_V POS 
WHERE POL.PO_HEADER_ID = POH.PO_HEADER_ID
AND POS.VENDOR_ID = POH.VENDOR_ID
GROUP BY VENDOR_NAME
HAVING SUM(UNIT_PRICE * QUANTITY) >= 1000


9. --List Supplier and its open PO counts
SELECT VENDOR_NAME,COUNT(DOCUMENT_STATUS) AS OPEN_COUNT
FROM PO_HEADERS_ALL POH,POZ_SUPPLIERS_V POS
WHERE POH.VENDOR_ID = POS.VENDOR_ID 
AND DOCUMENT_STATUS = 'OPEN'
GROUP BY VENDOR_NAME 

10. --List of Partially Paid invoices with Supplier Name(Supplier, Business Unit , Invoice Number, Open Invoice Amount)
SELECT 
HRO.NAME AS BUINESS_UNIT,API.INVOICE_NUM AS INVOICE_NUMBER,
(INVOICE_AMOUNT-AMOUNT_PAID) AS OPEN_INVOICE_AMT,POS.VENDOR_NAME AS SUPPLIER
FROM
HR_ALL_ORGANIZATION_UNITS HRO,
AP_INVOICES_ALL API,
POZ_SUPPLIERS_V POS
WHERE 
(INVOICE_AMOUNT-AMOUNT_PAID) > 0
AND
API.ORG_ID=HRO.ORGANIZATION_ID
AND 
HRO.OBJECT_VERSION_NUMBER=POS.OBJECT_VERSION_NUMBER

11. --List the invoices which is having PO details
SELECT DISTINCT INVOICE_NUM,PO_HEADER_ID
FROM AP_INVOICES_ALL 
WHERE PO_HEADER_ID = PO_HEADER_ID

12. --Write the Cancelled AP Invoice List between 1-Jan-2021 to 30-Jun-2021


Customer/OM/AR :

1. --Build a query for Active Customer List
SELECT DISTINCT HZP.PARTY_NAME,HZCA.STATUS FROM HZ_PARTIES HZP,HZ_CUST_ACCOUNTS HZCA
WHERE HZP.PARTY_ID = HZCA.PARTY_ID
AND HZCA.STATUS = 'A'

2. --List the Customer those are belongs to Country ‘US’
SELECT DISTINCT HZP.PARTY_NAME,HZP.COUNTRY 
FROM HZ_PARTIES HZP,HZ_CUST_ACCOUNTS HZCA
WHERE HZP.PARTY_ID = HZCA.PARTY_ID
AND COUNTRY = 'US'

3. --Build a query for Customer those who are Inactivated during last 6 months
SELECT HZP.PARTY_NAME,HZCAS.END_DATE AS END_DATE 
FROM HZ_PARTIES HZP,HZ_PARTY_SITES HZPS,HZ_CUST_ACCT_SITES HZCAS 
WHERE HZP.PARTY_ID = HZPS.PARTY_ID 
AND HZPS.PARTY_SITE_ID = HZCAS.PARTY_SITE_ID 
AND HZCAS.END_DATE < SYSDATE 
AND HZCAS.END_DATE > ADD_MONTHS(SYSDATE, -300)

4. --Write a query for active customer Count based on the business Unit.
SELECT HZP.PARTY_NAME AS CUSTOMER,RACTL.SALES_ORDER AS ORDER_NUM,COUNT(RACT.CUSTOMER_TRX_ID) AS AR_INVOICE_COUNT 
FROM HZ_PARTIES HZP,HZ_CUST_ACCOUNTS HZCA,RA_CUSTOMER_TRX_ALL RACT,RA_CUSTOMER_TRX_LINES_ALL RACTL 
WHERE HZP.PARTY_ID = HZCA.PARTY_ID 
AND HZCA.CUST_ACCOUNT_ID = RACT.SOLD_TO_CUSTOMER_ID 
AND RACT.CUSTOMER_TRX_ID = RACTL.CUSTOMER_TRX_ID 
GROUP BY HZP.PARTY_NAME,RACTL.SALES_ORDER

5. --Build a query for Order count based on its status
SELECT COUNT(ORDER_NUMBER),STATUS_CODE  
FROM DOO_HEADERS_ALL
GROUP BY STATUS_CODE

6.       Build a query to get the Customer and its AR Invoice count which is based on Sales Order

7.       Build a query to get AR Invoices Due date more than 50 days

8.       Build a query to get the AR Invoice details with the following bucket details

 

Customer Name, Inv Count(0-30days), Inv Count(31-60days), Inv Count(>60days)



9.       List the Incomplete state invoices

10.   List the Customer which is not having Bill to Site.


Regards,

B. Muthukrishnan
